include: package:flutter_lints/flutter.yaml

formatter:
  page_width: 120

linter:
  rules:
    - prefer_single_quotes
    - unawaited_futures
analyzer:
  exclude:
    - build/**
    - windows/**
    - macos/**
    - linux/**
